### ISSUE TITLE
Zmq function failed with EINTR errno when log rotation happened

### ISSUE THREAD

**Issue by mint570** [sonic-net/sonic-sairedis#1106]
In orchagent, the [SIGHUP handler](https://github.com/sonic-net/sonic-swss/blob/9eb44220819acca2fb8d4740443aee53f1f77061/orchagent/main.cpp#L325) is used for log rotation purpose. When signaling happens, zmq functions might fail with EINTR errno.
We should do retry in [ZeroMQChannel.cpp](https://github.com/sonic-net/sonic-sairedis/blob/ffc410969a907836c4d66165ab4738b9a54a6e65/lib/ZeroMQChannel.cpp) if zmq functions fail with EINTR.

**Comment by kcudnik** [comment]
when did you catched this ?

**Comment by mint570** [comment]
> when did you catched this ?

We recently enabled zmq in our device and found this issue.
