### ISSUE TITLE
Missing the branch recursive_search_file in repo Spacetown/gcovr

### ISSUE THREAD

**Issue by xumia** [sonic-net/sonic-sairedis#1178]
missing the branch recursive_search_file in repo https://github.com/Spacetown/gcovr.git

@kcudnik , can we use the other branch?

See build log: https://dev.azure.com/mssonic/build/_build/results?buildId=190790&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=6177235f-d4f1-5f72-835a-90ebb93a1784

```
error: pathspec 'origin/recursive_search_file' did not match any file(s) known to git
```

**Comment by saiarcot895** [comment]
Fixed in #1174, needs to be backported to release branches.
