### ISSUE TITLE
Flooding of setApiLogLevel() traces during boot up

### ISSUE THREAD

**Issue by jaganbal-a** [sonic-net/sonic-sairedis#1295]
Below set of traces get logged during phy_create_switch() and twice for each phy_create_port() totals 2820 traces per namespace with 6PHY devices. 
With 3 name space on the line card SKU 88_LC_36_FH_MO, 8460 traces logged during bootup. 

To suppress these traces during normal bootup, move the below trace log level from notice to info.
https://github.com/sonic-net/sonic-sairedis/blame/master/syncd/SaiDiscovery.cpp#L316

>>Log Snippet per side of a phy_create_port()
Sep 13 15:05:59.678988 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SWITCH
Sep 13 15:05:59.679012 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_PORT
Sep 13 15:05:59.679012 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_FDB
Sep 13 15:05:59.679028 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_VLAN
Sep 13 15:05:59.679028 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_VIRTUAL_ROUTER
Sep 13 15:05:59.679044 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_ROUTE
Sep 13 15:05:59.679044 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_NEXT_HOP
Sep 13 15:05:59.679054 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_NEXT_HOP_GROUP
Sep 13 15:05:59.679054 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_ROUTER_INTERFACE
Sep 13 15:05:59.679099 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_NEIGHBOR
Sep 13 15:05:59.679099 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_ACL
Sep 13 15:05:59.679110 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_HOSTIF
Sep 13 15:05:59.679116 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_MIRROR
Sep 13 15:05:59.679139 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SAMPLEPACKET
Sep 13 15:05:59.679139 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_STP
Sep 13 15:05:59.679139 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_LAG
Sep 13 15:05:59.679139 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_POLICER
Sep 13 15:05:59.679139 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_WRED
Sep 13 15:05:59.679151 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_QOS_MAP
Sep 13 15:05:59.679160 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_QUEUE
Sep 13 15:05:59.679160 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SCHEDULER
Sep 13 15:05:59.679175 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SCHEDULER_GROUP
Sep 13 15:05:59.679182 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_BUFFER
Sep 13 15:05:59.679182 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_HASH
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_UDF
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_TUNNEL
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_L2MC
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_IPMC
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_RPF_GROUP
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_L2MC_GROUP
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_IPMC_GROUP
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_MCAST_FDB
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_BRIDGE
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_TAM
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SRV6
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_MPLS
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_DTEL
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_BFD
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_ISOLATION_GROUP
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_NAT
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_COUNTER
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_DEBUG_COUNTER
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_MACSEC
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_SYSTEM_PORT
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_MY_MAC
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_IPSEC
Sep 13 15:05:59.679343 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_CRITICAL on SAI_API_BMTOR
Sep 13 15:05:59.681701 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SWITCH
Sep 13 15:05:59.681701 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_PORT
Sep 13 15:05:59.681701 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_FDB
Sep 13 15:05:59.681715 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_VLAN
Sep 13 15:05:59.681715 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_VIRTUAL_ROUTER
Sep 13 15:05:59.681722 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_ROUTE
Sep 13 15:05:59.681722 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_NEXT_HOP
Sep 13 15:05:59.681728 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_NEXT_HOP_GROUP
Sep 13 15:05:59.681763 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_ROUTER_INTERFACE
Sep 13 15:05:59.681763 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_NEIGHBOR
Sep 13 15:05:59.681773 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_ACL
Sep 13 15:05:59.681790 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_HOSTIF
Sep 13 15:05:59.681790 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_MIRROR
Sep 13 15:05:59.681790 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SAMPLEPACKET
Sep 13 15:05:59.681790 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_STP
Sep 13 15:05:59.681826 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_LAG
Sep 13 15:05:59.681826 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_POLICER
Sep 13 15:05:59.681849 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_WRED
Sep 13 15:05:59.681849 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_QOS_MAP
Sep 13 15:05:59.681849 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_QUEUE
Sep 13 15:05:59.681849 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SCHEDULER
Sep 13 15:05:59.681859 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SCHEDULER_GROUP
Sep 13 15:05:59.681870 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_BUFFER
Sep 13 15:05:59.681870 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_HASH
Sep 13 15:05:59.681870 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_UDF
Sep 13 15:05:59.681882 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_TUNNEL
Sep 13 15:05:59.681903 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_L2MC
Sep 13 15:05:59.681935 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_IPMC
Sep 13 15:05:59.681935 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_RPF_GROUP
Sep 13 15:05:59.681946 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_L2MC_GROUP
Sep 13 15:05:59.681946 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_IPMC_GROUP
Sep 13 15:05:59.681956 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_MCAST_FDB
Sep 13 15:05:59.681965 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_BRIDGE
Sep 13 15:05:59.681974 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_TAM
Sep 13 15:05:59.681974 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SRV6
Sep 13 15:05:59.681988 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_MPLS
Sep 13 15:05:59.681997 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_DTEL
Sep 13 15:05:59.682005 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_BFD
Sep 13 15:05:59.682014 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_ISOLATION_GROUP
Sep 13 15:05:59.682020 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_NAT
Sep 13 15:05:59.682029 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_COUNTER
Sep 13 15:05:59.682038 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_DEBUG_COUNTER
Sep 13 15:05:59.682047 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_MACSEC
Sep 13 15:05:59.682056 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_SYSTEM_PORT
Sep 13 15:05:59.682056 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_MY_MAC
Sep 13 15:05:59.682071 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_IPSEC
Sep 13 15:05:59.682071 sonic NOTICE gbsyncd0#GBSAI[14]: :- setApiLogLevel: Setting SAI loglevel SAI_LOG_LEVEL_NOTICE on SAI_API_BMTOR

**Comment by kcudnik** [comment]
I will move this to info level

**Comment by kcudnik** [comment]
Added fix here: https://github.com/sonic-net/sonic-sairedis/pull/1296

**Comment by abdosi** [comment]
PR is merged so closing it.
