### ISSUE TITLE
Warmboot: It will remain warm removeswitch when first reboot after warm-reboot

### ISSUE THREAD

**Issue by copyandrun** [sonic-net/sonic-sairedis#1361]
When first warm-reboot, the warm will be set by setRestartWarmOnAllSwitches(true). Then the syncd will be start with warm true. But there is no false set to SAI after warm get reconciled. So the next reboot will call warm SAI removeswitch. I think it should be a false set to SAI after warm-reboot.

**Comment by kcudnik** [comment]
not sure about this scenario, i believe when first warm reboot is performed, this flag is auromatically cleaned, but i'm not sure 
+@yxieca

**Comment by copyandrun** [comment]
I am sure this is warm because i add some log in the warm remove SAI code. When the first warm is down, i reboot to check it with warm remove

**Comment by yxieca** [comment]
I agree with Kamil. Next shutdown won't have warm reboot flag set. SAI shouldn't persist the warm shutdown or recover flag.

**Comment by copyandrun** [comment]
> I agree with Kamil. Next shutdown won't have warm reboot flag set. SAI shouldn't persist the warm shutdown or recover flag.

So it should just be used when remove not create. But the SAI create switch keep this flag true when warmboot. 
Should it be explicitly set to false by syncd instead of SAI?

**Comment by kcudnik** [comment]
What do you mean that sai create switch keep this true? In what sense ?

**Comment by kcudnik** [comment]
from SAI or sonic persprctive we don't look int what vendor is doing inside, for us that should not be concearn

**Comment by copyandrun** [comment]
> from SAI or sonic persprctive we don't look int what vendor is doing inside, for us that should not be concearn
> 
> is current implementaion causing some problems for you ? at which point you want to set this to false?

In syncd run shutdown
![image](https://github.com/sonic-net/sonic-sairedis/assets/75425799/f2d63a52-a82c-4c54-ac7e-de8950961fe8)
As you can see the warm set to true, maybe add else if cold set to false in front of the removeswitch? I guess it can work.

**Comment by copyandrun** [comment]
> I don't get the problem the flag should be set to true only if warm restart is requested not in else case which is not present here, can you describe step by step scenario what you want to achieve here ? I have hard time to understand this since so far many many times our scenario works fine in production and we don't have any issues

Step
1. warm-reboot 
2. device get ready
3. reboot or stop syncd
The problem is that in step 3 the SAI take it as warm remove_switch. But it should be cold.

I think step 1 set the warm flag to SAI in the code picture. And then SAI remove swtich and create switch since it is warm recovery. Then the warm is finished, but no one set the flag to false . So now stop syncd or reboot will make the SAI take it as warm remove_switch.
I got your point that the SAI should not keep the flag. I agree with you.
But now the bcm SAI is not work as we expected. So i think we can just set it to false when syncd ask to cold remove_switch.

**Comment by kcudnik** [comment]
If you reboot or stop sync you should do that gracefully ether by request shutdown or by OA which will set type of shutdown whether cold or warm or fast and it should be fine

**Comment by kcudnik** [comment]
Even if after warm reboot warm flag persist on sai then OA request of reboot will force new flag for example cold or boot, so of switch think that is in warm shutdown for next reboot it does not matter since OA will force to override that

**Comment by copyandrun** [comment]
> Even if after warm reboot warm flag persist on sai then OA request of reboot will force new flag for example cold or boot, so of switch think that is in warm shutdown for next reboot it does not matter since OA will force to override that

The situation I encountered was not being forced to write cold. Where is the override process code in OA?（I am sorry that i have not find that.）
(Just run the reboot command is what i did. Is it gracefully?)

**Comment by kcudnik** [comment]
yes, reboot is fine, should be fine, you mean reboot command as linux comman ? that would trigger cold boot and

**Comment by copyandrun** [comment]
> yes, reboot is fine, should be fine, you mean reboot command as linux comman ? that would trigger cold boot and

SONiC reboot command

**Comment by copyandrun** [comment]
> this is ok, do you see some negative issues with your scenario ?

The problem is that the last reboot goes with warm remove_switch. This will ignore the cold table remove code i added in the brcm SAI.
What i suggest is add the force set cold in syncd. I tested and i think i have solved it in my scenario.
Thank you.

**Comment by kcudnik** [comment]
Do you have pr ?

**Comment by copyandrun** [comment]
> Do you have pr ?

I think it just an issue in my scenario with brcm SAI change not SONiC issue. I will just close this issue.
Thank you for your reply.
